### ISSUE TITLE
Add global phase gate to Qiskit Terra

### ISSUE THREAD

**Issue by kevinsung** [qiskit-advocate/qamp-fall-22#1]
### Description

A gate that introduces a global phase. See https://github.com/Qiskit/qiskit-terra/issues/8236.

### Deliverables

Fix https://github.com/Qiskit/qiskit-terra/issues/8236.

### Mentors details

- Mentor 1
  - Name: Kevin Sung
  - GitHub ID: kevinsung
  - What they do: Qiskit Researcher

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Basic knowledge of Qiskit, Python, git, and quantum computing
  - Nice to have:
    - experience contributing to Qiskit

**Comment by sergiomtzlosa** [comment]
~~Hi,~~

~~Sergio here, this problem seems appealing to me 🤔. Please can you give some more details? Thanks!~~

**Comment by kevinsung** [comment]
@sergiomtzlosa you can post any questions you have at the Terra issue https://github.com/Qiskit/qiskit-terra/issues/8236. There is already some discussion ongoing there.

**Comment by Pranshi24** [comment]
Hi @kevinsung   I am interested in working on this project, I am working as a Quantum Researcher at Deloitte, and I have experience in using Qiskit as well. This will be a good experience for me. Let me know if we can connect on Slack to discuss more.

**Comment by sumit-kale** [comment]
@GemmaDawson

**Comment by kevinsung** [comment]
thank you @Pranshi24 , but @sumit-kale has already been matched with this project.

**Comment by sumit-kale** [comment]
The slides for Checkpoint 1 could be found below

[Presentation Checkpoint 1.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9735164/Presentation.Checkpoint.1.pdf)

It covers the proposal motivation and objective behind this issue.

**Comment by sumit-kale** [comment]
Checkpoint#2 

We worked on the mathematical definition of the gate and wrote the code for its implementation. We introduced a new class GlobalPhaseGate which creates a global phase (gphase) gate (e^{i\theta}) given the phase value theta. We are testing the code and will soon submit a PR.   

A visual representation of the project is attached 

![Image](https://user-images.githubusercontent.com/35228896/199847595-64d83893-4478-4784-84b6-729484fc42a5.png)

**Comment by sumit-kale** [comment]
Checkpoint Final Showcase 

Submitted a PR `Adding global_phase gate in qiskit-terra #9251`. 

The link to the presentation slides is below 
[Final_showoff_Dec_8.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10251791/Final_showoff_Dec_8.pdf)

The presentation covers motivation, objectives, and achievements.

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
