### ISSUE TITLE
Exploring expressibility of parametrized quantum circuits on IBMQ hardware

### ISSUE THREAD

**Issue by cnktysz** [qiskit-advocate/qamp-fall-22#10]
### Description

Variational quantum algorithms employ parametrized quantum circuits (PQCs). The choice of PQC has a huge impact on the performance of the algorithm, as it determines the accessible states on the Hilbert Space. For this reason, there is a need for a methodology or a measure that can quantify the performance of PQCs. In 2019, Sim et al. proposed two measures, namely Expressibility and Entangling Capability, to address this issue.  Although, their method works well for small number of qubits, it gets computationally expensive to analyze PQCs with large number of qubits. This project aims to implement an efficient way to compute the Expressibility of PQCs leveraging the freely available IBMQ resources.

[Reference paper](https://arxiv.org/abs/1905.10876)

### Deliverables

Implement a framework that can compute Expressibility of PQCs on IBMQ hardware.
Obtain consistent results with the original work and extend it to more qubits.
A blog post or a poster presentation at a relevant conference (Depends on the amount of progress).

### Mentors details

- Mentor
  - Name: Cenk Tüysüz
  - GitHub ID: @cnktysz
  - What they do: Physics PhD student, Qiskit Advocate

### Number of mentees

1

### Type of mentees

- Mentee
  - Required:
    - Interested in quantum computing research
    - Interested in running quantum circuits on IBMQ hardware
  - Nice to have:
    - Experience in translating mathematical expressions to code
    - Experience in building and executing quantum circuits with Qiskit

**Comment by sar49** [comment]
I am really intrigued by this project and would be interested in discussing this more with you Cenk!

**Comment by rkfqns13** [comment]
I am interested in this project. I have experience implementing quantum algorithms using IBMQ hardware. 
I want to use various quantum hardware, so I think this project will help me a lot to experience it.
I'd really like to join it!

**Comment by saktar-lanl** [comment]
@GemmaDawson, I am mentee on this project.

**Comment by saktar-lanl** [comment]
Presentation for Checkpoint-1: [#10-QAMP-2022-Checkpoint-1.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9738315/10-QAMP-2022-Checkpoint-1.pdf)

**Comment by saktar-lanl** [comment]
Expressibility of parameterized quantum circuits (PQCs) determines the ability to generate or explore states in the Hilbert space. The goal of this project is to implement an efficient way of measuring the expressibility of PQCs. In [1], expressibility is defined as the KL divergence [2] between estimated fidelity distribution and probability distribution from Haar-random unitary.

$Expr = D_{KL} (P_{PQC}(F;\theta) || P_{Haar}(F))$

Here, $P_{PQC}(F;\theta)$ represents the estimated fidelity distribution from PQCs as a histogram, and $P_{Haar}(F)$ represents the probability density function of fidelities for an ensemble of Haar random states. Lower KL divergence refers to better expressibility of PQCs or more closeness to the Haar random states. In this work, we reproduced the original results from [1] for different PQCs with multiple layers. To compute fidelity distribution, we used the IBMQ state vector simulator to get state vectors from the circuits and evaluated state fidelity between the state vectors using the Qiskit provided function. For single-qubit and 4-qubit circuits, we achieved almost similar results as the original results. The following plots show expressibility as $D_{KL}$ for PQC with an arbitrary unitary operator from [1] (b) and from our reproduced result (c).

<img width="210" alt="Screen Shot 2022-11-02 at 11 14 11 AM" src="https://user-images.githubusercontent.com/57744951/199561085-6883e2b1-9065-4851-afd4-0dd9afb99417.png"><img width="250" alt="Screen Shot 2022-11-02 at 11 14 34 AM" src="https://user-images.githubusercontent.com/57744951/199559264-2fc6f8f8-647a-4a66-8a5b-117cc8d60774.png"> <img width="255" alt="Screen Shot 2022-11-02 at 11 14 34 AM" src="https://user-images.githubusercontent.com/57744951/199569776-43f94032-058c-415d-98bf-a41bcd7eba62.png"><p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (a) Arbitrary Unitary &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;  (b) $D_{KL}$ from [1] &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;  (c) $D_{KL}$ reproduced </p>

However, this expressibility computation method becomes expensive with an increasing number of qubits. As an alternative, we choose to use the SWAP test [3] to compute the closeness between two states (i.e. fidelity). SWAP test requires $\mathcal{O}(\frac{1}{\epsilon^2})$ number of circuit execution where $\epsilon$ refers to additive error. We first compute fidelity by applying the SWAP test to two parameterized circuits using 10,000 shots and compute fidelity as $F = 1-\frac{2}{N} \sum_{i=1,..., N} C_i$ where $N$ is the number of shots and $C_i$ denotes the measurement as 0 or 1. Then we compute KL divergence for circuit ID-15 from [1] like previously using the fidelity distribution obtained using the SWAP test and Haar random distribution.  We repeat the process for multiple layers of the circuit (layer =1 to 5) and compare our obtained result with the original result. The following plots show the circuit-15 (a), our SWAP test implementation (b), and a comparison of the expressibility as KL divergence between the original results from [1] and our obtained results using the SWAP test.

<img width="250" alt="Screen Shot 2022-11-02 at 1 47 19 AM" src="https://user-images.githubusercontent.com/57744951/199568217-14ce4b5f-f775-4d9c-b8df-ef44a959ef86.png"><img width="250" alt="Screen Shot 2022-11-02 at 1 12 27 AM" src="https://user-images.githubusercontent.com/57744951/199568040-a80fcaf5-8cf9-4ead-8080-513cccd39e5e.png"><img width="300" alt="Screen Shot 2022-11-02 at 1 12 27 AM" src="https://user-images.githubusercontent.com/57744951/199573852-bcfc0dd1-61b7-4f13-9533-e7b076f3c7ee.png">
<p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (a) Circuit ID-15 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp;  &nbsp;  (b) Our SWAP test implementation &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;   (c) $D_{KL}$ using SWAP test </p>

From the above plot (c), we can see that the SWAP test approach for computing state fidelity outperforms the original results from [1]. Next, we are going to perform experiments on IBM hardware to obtain fidelity distribution and study the number of shots required to achieve stable fidelities. Additionally, we will analyze the effect of hardware noise on expressibility.

References:
[1] Sim, Sukin, Peter D. Johnson, and Alán Aspuru‐Guzik. "Expressibility and entangling capability of parameterized quantum circuits for hybrid quantum‐classical algorithms." Advanced Quantum Technologies 2, no. 12 (2019): 1900070.
[2] https://en.wikipedia.org/wiki/Kullback–Leibler_divergence
[3] https://en.wikipedia.org/wiki/Swap_test

**Comment by GemmaDawson** [comment]
@saktar-unr - please upload your Final Showcase presentation materials, and if needed, update the project Title and/or description.

**Comment by saktar-lanl** [comment]
Presentation: [#10-QAMP-2022-Checkpoint-Final.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/10262240/10-QAMP-2022-Checkpoint-Final.pptx)
Recording: https://drive.google.com/file/d/1Px3HOmGI4AmN17NchqD6IBN6SVNQeC5p/view?usp=sharing

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
