### ISSUE TITLE
[mentees propose]A quantum network simulatior open source library based on qiskit-terra backend

### ISSUE THREAD

**Issue by poig** [qiskit-advocate/qamp-fall-22#11]
### Description

The idea is to make an open source library that can simulate quantum networks like [netqasm](https://github.com/QuTech-Delft/netqasm) with the structure of [SeQUeNCe](https://github.com/sequence-toolbox/SeQUeNCe) library that based on qiskit-terra backend and having some of those interesting and useful tools that might be desirable for the researcher and also for a better education purpose. 
Note: this will be a large project, expect at least get any responses on the possibility/advice of this open sources library idea

Reference:
- [more detail about the idea of the library](https://github.com/mgg39/qiskit-networks/discussions/12)
- [planning library structure](https://github.com/mgg39/qiskit-networks/discussions/15)
- [reference for desire component](https://github.com/mgg39/qiskit-networks/discussions/14)

### Deliverables

An extended version of the quantum network simulator exists, that can contain more desirable modules, is compatible with other Qiskit libraries for example designing quantum data center circuits with qiskit-metal or machine learning for cryptanalysis with qiskit-machine-learning, and has a visualization GUI like Qiskit-metal.

#### to be determine
- Mentor 1
  - Name:
  - GitHub ID:
  - What they do:
- Mentor 2
  - Name:
  - GitHub ID:
  - What they do:

### Number of mentees

5

#### to be determine
- All Mentee
  - Required:
    - interested in Quantum network, time to stick with this project.
    - prior experience with at least one of the quantum network simulator like[QuNetSim](https://github.com/tqsd/QuNetSim), [SeQUeNCe](https://github.com/sequence-toolbox/SeQUeNCe), [netqasm](https://github.com/QuTech-Delft/netqasm), [SimulaQron](https://github.com/SoftwareQuTech/SimulaQron), [ProjectQ](https://github.com/ProjectQ-Framework/ProjectQ), 
    - good programming skills
  - Nice to have:
      - good understanding of Quantum network, listed [here](https://github.com/mgg39/qiskit-networks/discussions/12#discussioncomment-3077213)
      - good understanding of Quantum information
      - good in qiskit-metal
      - good understanding with qiskit library

**Comment by poig** [comment]
will reopen during the application period

**Comment by HuangJunye** [comment]
@poig Thanks for proposing your own project idea. You indicated 5 in the mentee field. Does it mean that you are open to other mentees joining the project?

**Comment by poig** [comment]
> @poig Thanks for proposing your own project idea. You indicated 5 in the mentee field. Does it mean that you are open to other mentees joining the project?

yes

**Comment by GemmaDawson** [comment]
Unfortunately, this project will not be continuing in QAMP Fall 2022
