### ISSUE TITLE
What is possible with quantum computers today?

### ISSUE THREAD

**Issue by zlatko-minev** [qiskit-advocate/qamp-fall-22#13]
### Description

Be part of growing and dynamic research team that seeks to understand and push the boundaries of possible with quantum computers today. We will work with Qiskit and the Quantum devices, running experiments on the devices and trying various approaches to push quantum experiments, such as in quantum simulations or other fields, to the edge of what is possible in the noisy era of quantum computing.

### Deliverables

- experimental results on IBM quantum devices related to ongoing demonstration projects

### Mentors details

- Mentor 1
  - Name: zlatko minev
  - GitHub ID: zlatko.Minev
  - What they do: Team manager and technical lead of Qiskit Leap Research
- Mentor 2
  - Name:  Qiskit Leap team
  - GitHub ID:
  - What they do: Awesome quantum research 

### Number of mentees

2

### Type of mentees

- Mentee 1
  - Required: working operational knowledge of Qiskit and running Quantum experiments on IBM quantum devices
  - Nice to have: experience with more advanced Qiskit features - runtime, pulse, transpiler, 
    - error mitigation techniques
- Mentee 2 - sam 
  -

**Comment by MarcoBarroca** [comment]
I'm working on chemistry simulations with Qiskit for applications in climate and sustainability. Searching for new materials for carbon capture and batteries for instance. Can you elaborate further on any possible applications that you might be considering? I'd be interested in joining this even if it's tangentially related as I'm interested in applications.

**Comment by BramDo** [comment]
I started with quantum computing at the moment IBM put the first 5 qubit processor online. I did a couple of Summer schools and challenges and saw the progress last year. If you combine error mitigation and optimizing we would be able get to the edge whats is possible for interesting applications. I also am interested in this quest, it is also my drive to do quantum computing. It would be great to hear about the possible applications, but i think that even speeding up simulation of LiH molecule on real backend with error mitigation will open new applications.

**Comment by jvscursulim** [comment]
Hi @zlatko-minev , I have an interest in joining this project. I have experience with QEC and VQE. Currently, I'm working on a benchmark for VQE. I also have experience with quantum experiments on IBM quantum devices, runtime and transpiler. About error mitigation, I just know https://qiskit.org/textbook/ch-quantum-hardware/measurement-error-mitigation.html.

**Comment by hamzakamel1** [comment]
I'm Hamza a new Qiskit advocate for 2022. I'm very interested in this project, I have a very good skills in research and coding skills. I have participated in Quantum Computing Hackathon before and I have the skill to find the information fast and correct at the same time. I would love to join this project.

**Comment by born-2learn** [comment]
I'm interested to work on this project and have applied! Thanks.

**Comment by helenup** [comment]
Hi, I am Helen Urgelles a new Qiskit Advocate. I am very interested in this project in order to improve my hardware skills. I’ve been working on software level especially, but I’ve executed many experiments on IBM quantum devices. I would really like to join you all.

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by born-2learn** [comment]
[QAMP Shadow Phases - Checkpoint 1 - Syed Farhan.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9794806/QAMP.Shadow.Phases.-.Checkpoint.1.-.Syed.Farhan.pptx)

**Comment by born-2learn** [comment]
**Current Update:** A Two-Qubit Hamiltonian was constructed representing H2-molecule at its equilibrium distance. The ground state energy was obtained by both diagonalizing the matrix and also by the VQE experiment. Classical shadows were then obtained by consecutively applying random unitaries and then measuring them in X, Y and Z bases. The machine learning model given in https://arxiv.org/abs/2106.12627 was analyzed to ensure compatibility with the current experiment and has been modified to train the classical shadows obtained from the two qubit hydrogen hamiltonian.   

**Next Steps:** Identifying a sophisticated hamiltonian, training the machine leanring algorithm with the classical shadows of this hamiltonian and finally predicting the ground state properties at the phase transition boundaries. 

### Project Workflow 
<img width="611" alt="ground_state_prediction" src="https://user-images.githubusercontent.com/42010556/202639183-dbc70dea-277f-4397-aca8-f79a5a843ee5.png">

**Comment by born-2learn** [comment]
@GemmaDawson @HuangJunye Please find the written update and image in the above comment. Thanks!

**Comment by born-2learn** [comment]
[QAMP Shadow Phases - Final Presentation.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/10230746/QAMP.Shadow.Phases.-.Final.Presentation.-.Syed.Farhan.pptx)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
