### ISSUE TITLE
Longform content for the Qiskit Blog

### ISSUE THREAD

**Issue by ryanfmandelbaum** [qiskit-advocate/qamp-fall-22#14]
### Description

Qiskit prides itself in running a weekly, open source blog featuring content by and for Qiskit users. The blog requires contributors in order to stay running. While much of these contributions consist of tutorial content and papers, we're also looking for creative work and to mentor writers interested in honing their science communication skills. After all, better science communicators in the quantum community can only benefit the field as a whole.

### Deliverables

Mentees will produce two long-form, narrative contributions to the Qiskit Blog. These should each be 800 words or longer, telling stories about important work, interesting people, or ongoing research in the Qiskit community. They should begin with well-researched briefs, will require interviews, and will require you work with any of the story's subjects to gather image, photo, or illustration assets. 

### Mentors details

- Mentor 1
  - Name: Ryan Mandelbaum
  - GitHub ID: ryanfmandelbaum
  - What they do: Qiskit Editorial Lead

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Fluent in English language written communication
    - Desire to produce non-technical science writing (i.e., for general audiences)
  - Nice to have:
    - Experience writing about physics for general audiences
    - Knowledge of quantum information

**Comment by gunchamalik** [comment]
Hi,
I am interested in taking part in this project. I have written an article on AI Ethics in the past. This will be a good opportunity for me to take that step on QC topics as well.

**Comment by smendoncabruna** [comment]
Very glad to be chosen for this project! :)

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by smendoncabruna** [comment]
Hi, there it is: 
[QAMP - Checkpoint 1.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9745522/QAMP.-.Checkpoint.1.pdf)

**Comment by smendoncabruna** [comment]
## Checkpoint 2 🏁

*Bruna Shinohara de Mendonça, November 1st, 2022.*

- **Related issue:** [Longform Content for the Qiskit Blog](https://github.com/qiskit-advocate/qamp-fall-22/issues/14).
- **Progress**
    
    Along with my mentor, we held weekly meetings to:
    
    - delimit possible writing subjects for the qiskit medium articles;
    - chose the first theme: Write about a recent manuscript from IBM Quantum researchers, titled “Preparing Majorana zero modes on a noisy quantum processor” ([link](https://arxiv.org/pdf/2206.00563.pdf)). The choice was based on my familiarity with the subject of topological systems simulation and the possibility of explaining qiskit concepts and showcasing applications;
    - discussed scientific writing techniques;
    - invited the authors for an interview held via webex;
    - drafted a couple of versions of the article.
    
- **Results so far**
    
    On October 26th, 2022, our first Qiskit Medium was published, titled “Simulating topological systems on noisy quantum computers using Qiskit”. Here is a screenshot of this first deliverable result:
    
![image](https://user-images.githubusercontent.com/67931926/199707987-670ff810-95e1-439c-bb7d-44cd675dc0fb.png)

The full text can be found in this [link](https://medium.com/qiskit/simulating-topological-systems-on-noisy-quantum-computers-using-qiskit-588bd13695f7).

- **Current and future steps**

At the moment, we are conducting and inviting specialists for our next Qiskit Medium blog post. After the interviews are finished, we should work on the full article to be delivered during the QAMP duration.

**Comment by smendoncabruna** [comment]
Hi, here is the final show case for this QAMP issue:
[QAMP - Checkpoint 3.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10231646/QAMP.-.Checkpoint.3.pdf)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
