### ISSUE TITLE
Building out Qiskit Quantum Error Correcting 

### ISSUE THREAD

**Issue by ghost** [qiskit-advocate/qamp-fall-22#15]
### Description

Qiskit QEC  (https://github.com/qiskit-community/qiskit-qec/issues) is an open source framework for quantum error correcting. 

If you've got a **theory background**, you'd have high freedom to work on either developing your own qec modules or working on pre-existing issues that require a theory background. Example: [theory issue](https://github.com/qiskit-community/qiskit-qec/issues/125)

If you've got a **software background**, you'd have high freedom to work on either creating a database for codes (QEC codes) or by working on some of the pre-existing issues. Example: [swe issue1](https://github.com/qiskit-community/qiskit-qec/issues/185)  [swe issue2](https://github.com/qiskit-community/qiskit-qec/issues/229)

If you've got a strong **graphics** background, you'd have high freedom to work on building dynamic tiling. Example: [graphics issue](https://github.com/qiskit-community/qiskit-qec/issues/235) 

[all current open issues ](https://github.com/qiskit-community/qiskit-qec/issues)

**Please note:** The mentee on this program will have lots of freedom and minimal oversight.  

### Deliverables

See Description 

### Mentors details

- Mentor 
  - Name: Grace 
  - GitHub ID: grace-harper-ibm
  - What they do: software dev in qec 

### Number of mentees

2

### Type of mentees

**>=2 mentees is better** so that they can collaborate together 

- Description for all mentees
  - Required:
    - at least one of: QEC background or python background or c++ background 
    - self-motivated

**Comment by Qcatty** [comment]
this seems a goood project for my group(we are 3 qiskit advocates)

**Comment by ghost** [comment]
Hey Khadija, 
That's great; we should plan a time to chat about the potential for this project?

**Comment by ssawarn** [comment]
I am interested in theory section. I would like to work on it @grace-harper-ibm

**Comment by dhruvbhq** [comment]
Hi @GemmaDawson, as you requested in the email, I have tagged you here.

**Comment by ruihao-li** [comment]
Hey @GemmaDawson! It's Ruihao here.

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by ruihao-li** [comment]
[QAMP15_checkpoint1.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9746520/QAMP15_checkpoint1.pdf)

**Comment by dhruvbhq** [comment]
[QAMP15_checkpoint2.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9922188/QAMP15_checkpoint2.pdf)
Hi @GemmaDawson , here is our report for QAMP checkpoint-2.

**Comment by ruihao-li** [comment]
[QAMP15_ Final_Slides.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10220660/QAMP15_.Final_Slides.pdf)
Hello @GemmaDawson, here's our slides for the final showcase. Below are the links to our PRs in Qiskit-QEC:
- https://github.com/qiskit-community/qiskit-qec/pull/259
- https://github.com/qiskit-community/qiskit-qec/pull/279
- https://github.com/qiskit-community/qiskit-qec/pull/281
- https://github.com/qiskit-community/qiskit-qec/pull/304
- https://github.com/qiskit-community/qiskit-qec/pull/305
@dhruvbhq

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
