### ISSUE TITLE
Work on the quantum algorithm tutorials

### ISSUE THREAD

**Issue by Cryoris** [qiskit-advocate/qamp-fall-22#17]
### Description

Qiskit implements a large number of quantum algorithms, ranging from ground and excitetd state search over time evolution to amplitude estimation. However, many algorithms lack a tutorial and it's not evident how the algorithms can be used and what all their abilities are.

As tutorials are one of the first touchpoints users have with Qiskit it's crucial they are up-to-date and cover all algorithms! :sligh

### Deliverables

Implement tutorials for algorithms in Qiskit Terra, such as
* excited state calculation with VQD
* phase and amplitude estimation
* time evolution

and possibly polish the existing ones and ensure they are up-to-date!

### Mentors details

- Mentor 1
  - Name: Julien Gacon
  - GitHub ID: @Cryoris
  - What they do: PhD student & Qiskit dev

### Number of mentees

2

### Type of mentees

- Mentee 1 & 2
  - Required:
    - Python knowledge
    - Motivation!
  - Nice to have:
    - If you used Qiskit algorithms before, that would be great!

**Comment by Christophe-pere** [comment]
Hello, 
I'm interested in this project. Phase and amplitude estimation are still a nightmare for me; it could be an excellent opportunity to go deeper. Could we schedule a call to discuss this further?

**Comment by gunchamalik** [comment]
Hi,
I am interested in working on this project. I have taken a hands-on session, for college students, in the past on Shor's algorithm. This will be a good opportunity for me to dive in a bit in other algorithms as well.

**Comment by gideonuchehara** [comment]
Hello @Cryoris , I am interested in this project. I have submitted my application for mentorship. Please, let me know what the next steps are. Looking forward to working with you. Thanks.

**Comment by AbhaSNK** [comment]
Hello Cryosis! 
This project is really interesting. I  have experience writing about quantum topics, in a way to make things easier for readers at various levels and will love making the code understandable and easy for all. I wish to write an extensive guide to quantum algorithms.  I am super okay with working with others and learn together!

**Comment by helenup** [comment]
Hi. I am Helen a new Qiskit Advocate. I am interested in working on this project. I’ve already worked with some algorithms and I would love to learn with the team. I’ve submitted my application. Thanks

**Comment by Cryoris** [comment]
It's great to see so much interest in this! However, we're currently undergoing a refactoring of the algorithms in Qiskit Terra to use the new Qiskit Primitives so it is a unfortunately a bit too early to write tutorials. Let me know you are still interested in the future, then we can tackle this project after the refactoring! 🙂
