### ISSUE TITLE
Variational, topology-aware synthesis of unitaries

### ISSUE THREAD

**Issue by Cryoris** [qiskit-advocate/qamp-fall-22#18]
### Description

Finding a circuit that implements an arbitrary unitary is a requirement in several algorithms, such as loading random distributions/data. Several algorithms for this purpose exist, but most of them ignore the qubit topologies and become less performant once the topology is taken into account.
The goal is to implement a topology-aware synthesis, which is based stepwise composition and numerical optimization. This can also be used to find better decompositions for existing circuits.

The plan for this project is to implement the algorithm in Towards Optimal Topology Aware Quantum Circuit Synthesis (Davis et al, 2020) and compare perfomance for arbitrary unitary synthesis against deterministic state-of-the art decomposition.

*Note* This project is a little involved but the outcome would be great!

### Deliverables

Benchmark of the algorithm and study on how we can improve algorithm-to-topology mappings.

### Mentors details

- Mentor 1
  - Name: Julien Gacon
  - GitHub ID: @Cryoris
  - What they do: PhD student & Qiskit dev

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Familiar with compilation techniques 
    - Good knowledge of Python and ideally Qiskit
  - Nice to have:
    - Research background

**Comment by KakashiOO7** [comment]
Hi @Cryoris,
It's looks quite interesting to I would be lucky to collaborate on this with you.
Hoping to hear from you soon.

Thank you

**Comment by Gaya3-mv** [comment]
Hi @Cryoris, this seems to be a very interesting research problem. I do wish to work on this and learn more. 
Thank you.

**Comment by Qcatty** [comment]
this seems an interesting project for me.
can you provide a link to the paper that going to be used as the reference for this project?

**Comment by GemmaDawson** [comment]
Unfortunately, this project cannot go forward at this time
