### ISSUE TITLE
Add Scipy MILP solver to Qiskit optimization

### ISSUE THREAD

**Issue by t-imamichi** [qiskit-advocate/qamp-fall-22#2]
### Description

The latest Scipy 1.9.0 introduced a mixed integer linear programming (MILP) solver. This project aims at developing a classical optimizer for Qiskit Optimization based on the Scipy MILP solver.

Note: this project might be fully "classical" project. No quantum might be involved.

References:
- [Scipy 1.9.0 release note](https://docs.scipy.org/doc/scipy/release.1.9.0.html#highlights-of-this-release)
- [API reference of scipy.optimize.milp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.milp.html#scipy.optimize.milp)

### Deliverables

Adds a new classical solver, e.g., `ScipyOptimizer`, to <https://github.com/Qiskit/qiskit-optimization/tree/main/qiskit_optimization/algorithms>

Resources
- [Qiskit optimization tutorial about classical solvers](https://qiskit.org/documentation/optimization/tutorials/11_using_classical_optimization_solvers_and_models.html)

### Mentors details

- Mentor 1
  - Name: Takashi Imamichi
  - GitHub ID: @t-imamichi
  - What they do: Qiskit Optimization developer

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Basic knowledge of Qiskit Optimization, Python, and git
  - Nice to have:
    - Basic knowledge of Scipy and mathematical optimization

**Comment by Dran-Z** [comment]
Hi Takashi-san, I would like to hone my coding skills and your project really fits it! I am a fresh Master's graduate in quantum engineering this year. I have some experience with both Python and Qiskit (specifically, I implemented several research papers in quantum algorithms using Qiskit). I would be happy if I could learn how to work on developing an open-source library through this project!

**Comment by t-imamichi** [comment]
@Dran-Z Hi. Thank you for having an interest in this project. As I wrote the description, this project focuses on the integration of a classical solver. Are you happy to work on it?

**Comment by Dran-Z** [comment]
> @Dran-Z Hi. Thank you for having an interest in this project. As I wrote the description, this project focuses on the integration of a classical solver. Are you happy to work on it?

Sure. I expect to practice my skill with developing a qiskit feature rather than learning quantum-algorithm-relevant knowledge. It will be nice if it is the case.

**Comment by t-imamichi** [comment]
FYI: https://qiskit.org/documentation/optimization/tutorials/11_using_classical_optimization_solvers_and_models.html

**Comment by t-imamichi** [comment]
We had the first meeting to introduce each other and discuss the project overview on Sep 13.

**Comment by Dran-Z** [comment]
The Checkpoint-1 slides can be found [here](https://github.com/Dran-Z/QAMP2022-MILP-solver/blob/main/slides/Checkpoint-1.pptx).

**Comment by Dran-Z** [comment]
For Checkpoint-2: Please see the [brief report](https://github.com/Dran-Z/QAMP2022-MILP-solver/blob/main/QAMP-Checkpoint-2.pdf) and the [figure](https://github.com/Dran-Z/QAMP2022-MILP-solver/blob/main/QAMP-Checkpoint-2.png)

**Comment by GemmaDawson** [comment]
@Dran-Z - please upload your Final Showcase presentation materials, and if needed, update the project Title and/or description.

**Comment by Dran-Z** [comment]
The final presentation is [here](https://github.com/Dran-Z/QAMP2022-MILP-solver/blob/main/slides/Last-Demonstration.pptx)!

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
