### ISSUE TITLE
Develop new intrinsics for matrix multiplication of complex values in Qiskit-Aer

### ISSUE THREAD

**Issue by hhorii** [qiskit-advocate/qamp-fall-22#22]
### Description

Qiskit-Aer supports [SIMD-based matrix multiplication in statevector](https://github.com/Qiskit/qiskit-aer/blob/main/src/simulators/statevector/qv_avx2.cpp) by using AVX2, which is the Intel's SIMD instruction set.
In this project, we develop implementation for other platform: Apple Silicon (M1, M2) and ppc64le.

To join this project, mentees need to have M1/M2 mac or POWER linux machines.

### Deliverables

New variation of `AER::QV::Transformer` for Apple Silicon and PowerPC.

### Mentors details

- Mentor 1
  - Name: Hiroshi Horii
  - GitHub ID: @hhorii
  - What they do: Lead of Qiskit-Aer development
- Mentor 2
  - Name: Jun Doi
  - GitHub ID:@doichanj
  - What they do: Lead of GPU supports in Qiskit-Aer

### Number of mentees

2

### Type of mentees

- Mentee 1
  - Required:
    - Has experiences in C++ and assemble development
    - Has development environment of Apple Silicon
  - Nice to have:
    - Experiences in statevector imlementation
    - Knowledge in Qiskit-Aer
- Mentee 1
  - Required:
    - Has experiences in C++ and assemble development
    - Has development environment of PowerPC
  - Nice to have:
    - Experiences in statevector imlementation
    - Knowledge in Qiskit-Aer

**Comment by archanaravindar** [comment]
Hi This project interests me as I have assembly background in PowerPC and C++. Pls let me know if there is a spot for a mentee available.

**Comment by GemmaDawson** [comment]
Unfortunately, this project will not go forward at this time.
