### ISSUE TITLE
Writing an Unity Plugin for Using a Qiskit Runtime using C#

### ISSUE THREAD

**Issue by TigrisCallidus** [qiskit-advocate/qamp-fall-22#24]
### Description

Qiskit runtime can be used from different programming environments not only python.

To make it easier for C#/Unity developers to use, it would be great to have an Unity Plugin which can directly call some runtime programs. Just as a first example for others to copy, or to directly use this plugin.

There are different possibilities for a runtime to be used. The mentee can even write a runtime themselves. 

Possible topics include:

- Randomness Generation
- Image Processing
- A topic the mentee is specialized in! This is quite open feel free to be creative!

The runtime should have some form of application, which should be demonstrated in an example in Unity.

### Deliverables

An easy to use unity plugin (on a github) including a unity package for easy installation.

The package should be make it possible to call a useful runtime directly from Unity/C# 

A simple example scene showing how to use this plugin (and what for) should also be included.

### Mentors details

- Mentor
  - Name: Marcel Pfaffhauser
  - GitHub ID: TigrisCallidus
  - What they do: Quantum Community Team Europe

### Number of mentees

1

### Type of mentees

- Mentee
  - Required:
    - Programming Knowledge in C#
    - Programming Knowledge in Qiskit
    - Interest in Qiskit Runtime
  - Nice to have:
    - Experience in Unity
    - Any special interest (Games, Optimization, Image Processing) which they want to tackle using Qiskit Runtime

**Comment by Faujdar** [comment]
Hey @GemmaDawson 
This is Jyoti, a mentee in this project.

**Comment by TigrisCallidus** [comment]
Hey @GemmaDawson
Tagging you as requested, and thank you for your work!

Marcel the Mentor of this project

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by Faujdar** [comment]
Here it is!!
[QAMPfall22_Checkpoint1_#24.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9752298/QAMPfall22_Checkpoint1_.24.pdf)

**Comment by Faujdar** [comment]
![IMG_20221106_230042](https://user-images.githubusercontent.com/37533715/200185740-cc7df630-3971-4113-a7c9-66adca7f5ae7.jpg)
