### ISSUE TITLE
Implement virtual distillation, an error mitigation technique, in Qiskit

### ISSUE THREAD

**Issue by derek-wang-ibm** [qiskit-advocate/qamp-fall-22#3]
### Description

Quantum error mitigation is ["the continuous path that will take us from today's quantum hardware to tomorrow's fault-tolerant quantum computers"](https://research.ibm.com/blog/gammabar-for-quantum-advantage). Error mitigation reduces the effects of noise to achieve the best performance with today's near-term intermediate-scale quantum (NISQ) devices. Several error mitigation techniques have already been implemented in Qiskit, such as readout error mitigation and dynamical decoupling.

[Virtual distillation](https://link.aps.org/doi/10.1103/PhysRevX.11.041036) is a new method for correcting errors in estimating observable by distilling out the desired quantum state from multiple virtual and noisy copies. In Qiskit, we have prototyped a [more resource-efficient version of this method](https://arxiv.org/abs/2105.01239) and demonstrated improvements in performance.

We would like to implement this method fully into Qiskit, potentially taking advantage of Qiskit Runtime, to enable broader use of this novel error mitigation technique and, ultimately, usage of IBM's quantum devices.

### Deliverables

PR request for virtual distillation for error mitigation and, potentially, a blog post and section in Qiskit Textbook's error mitigation chapter

### Mentors details

- Mentor 1
  - Name: Swarnadeep Majumder
  - GitHub ID: swarnadeep-majumder
  - What they do: Researcher on Qiskit Leap
- Mentor 2
  - Name: Alireza Seif
  - GitHub ID: alireza-seif
  - What they do: Researcher on Qiskit Leap
- Mentor 3
  - Name: Derek Wang
  - GitHub ID: Derek-Wang
  - What they do: Researcher on Qiskit Leap

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Experience contributing to open-source software and, specifically, Qiskit
  - Nice to have:
    - Basic knowledge of quantum information theory, including error characterization and error mitigation techniques

**Comment by zlatko-minev** [comment]
Great project and we get to work together

**Comment by BramDo** [comment]
This seems to be a great project, with great possibilities. I have som experience with contributing open source software also qiskit, but on a smaller scale like simple bug removal and test scripts.

**Comment by orielkiss** [comment]
Hi @GemmaDawson

**Comment by newsma** [comment]
Hi @GemmaDawson

**Comment by alirezaseif-ibm** [comment]
tag @GemmaDawson

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by orielkiss** [comment]
Material for check point 1
[VD.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9777442/VD.pptx)

**Comment by orielkiss** [comment]
[QAMP_22_VD.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9929695/QAMP_22_VD.pdf)
Here is the report and one figure summarizing the main results obtained at this stage @GemmaDawson

**Comment by orielkiss** [comment]
[Uploading VD_qamp.pdf…]()
Here are the slides of my presentations

**Comment by orielkiss** [comment]
Here are my slides @GemmaDawson [VD_qamp.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10185846/VD_qamp.pdf)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
