### ISSUE TITLE
QML for reduced order density matrix time propagation

### ISSUE THREAD

**Issue by pemmaras** [qiskit-advocate/qamp-fall-22#34]
### Description

Reduced density matrices (RDMs) play an important role in the theory of open quantum systems and functional approaches that aim to circumvent the exponential scaling associated with the full Hilbert space when approximating observable properties. This project aims to explore quantum machine learning (QML) of time propagators for evolving subsystem densities or density matrices of lattice models comprised of spin or Fermionic degrees of freedom. Our goal is to assess the architectural and data requirements associated with Quantum Neural Networks (QNNs) for accurately predicting the future non-Markovian time evolution of RDMs based on past histories. Our project aims to reproduce and extend recent research in this area: https://arxiv.org/abs/2201.11647  and will be conducted in collaboration with the Sanvito group at Trinity College Dublin, Ireland.

### Deliverables

The primary goal of this work is to conduct QML research into predicting the time evolution of quantum subsystems which will lead to a journal publication.
Additionally we hope to contribute QML models we develop to the quantum open source community in the form of Qiskit tutorials

### Mentors details

- Mentor 1
  - Name: Das Pemmaraju
  - GitHub ID: @pemmaras
  - What they do: Computational Physicist and Qiskit Advocate

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    -  Graduate level Quantum Mechanics coursework
  - Nice to have:
    - Qiskit coding experience
    - QML basics

**Comment by hykavitha** [comment]
@pemmaras  @HuangJunye  : Hey both, This fits my area. At my day job I do QML, Would like to contribute to this work.

**Comment by ichen17** [comment]
It's interesting for me. I have some knowledge of QML and also the quantum open system. I also like to contribute to this project.

**Comment by pemmaras** [comment]
Hi @hykavitha, @ichen17  Thank you for your interest! Are you applying to the QAMP fall 22 program? If so, please indicate your interest  on the application form. If you are not applying via the QAMP program there might also be an opportunity to collaborate. Reach out to me (@Das Pemmaraju) over Qiskit slack and we can discuss options.

**Comment by hykavitha** [comment]
@pemmaras  : I'm working on issue number #35 so will drop from this.

**Comment by Siheon-Park** [comment]
@GemmaDawson I have been mailed to add a comment on this issue. Sorry for the late response.

**Comment by pemmaras** [comment]
Slides from Checkpoint 1
[QAMP-Project34-Checkpoint1.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9740083/QAMP-Project34-Checkpoint1.pptx)

**Comment by pemmaras** [comment]
Checkpoint-2
[Project-34-Checkpoint-2.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9936473/Project-34-Checkpoint-2.pdf)
![1-4-1-DQNN-schematic](https://user-images.githubusercontent.com/83732883/199929710-10de5274-233e-4f86-ad31-b1efccf51b20.jpg)

**Comment by pemmaras** [comment]
[Project-34-FinalPresentation.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/10241464/Project-34-FinalPresentation.pptx)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
