### ISSUE TITLE
Variational method/s for solving continuous equations

### ISSUE THREAD

**Issue by Hirmay** [qiskit-advocate/qamp-fall-22#36]
### Description

We will investigate the application of the Variational methods for solving continuous problems. Simple problems such as the Brachistochrone problem could be divided into different sections according to the accuracy one wants. One would need to discretize the actions one can take and choose one of the actions which optimize the (time in this case) constraints. We would utilize quantum simulators and real quantum devices to obtain results and compare them to the classically obtained solution. We could also apply some error mitigation techniques to improve the results obtained from a quantum computer.

### Deliverables

A research paper demonstrating the results obtained via simulation and running it on a quantum computer. Suggest some improvements one can make (and implement them) and apply some error mitigation techniques to improve outcomes.

### Mentors details

- Mentor 1

### Number of mentees

2

### Type of mentees

- Mentee 1
  - Name: Hirmay Sandesara
  - GitHub ID: @Hirmay
  - Slack: @ Hirmay Sandesara
  - What they do: Qiskit Advocate and an undergraduate student with majors in CSE. 
 - Mentee 2
  - Name: 
  - GitHub ID: @ichen17

PS: I don't know how many mentees are required (the mentor would decide), but two seem sufficient now.

**Comment by ichen17** [comment]
It's interesting for me. I would like to contribute to it.

**Comment by Hirmay** [comment]
Okay, great! You want to be a mentee, right?

**Comment by ichen17** [comment]
Right. I want to be a mentee of this project.

**Comment by Hirmay** [comment]
Okay, great! Welcome to the team!

**Comment by ssawarn** [comment]
It indeed seems a great problem to work on, but alas the seats are filled.

**Comment by Hirmay** [comment]
The problem isn't the number of mentees available (which could be incremented). The problem is finding a mentor for this project.

**Comment by Qcatty** [comment]
I would like to join tooo, as a mentee

**Comment by Hirmay** [comment]
Hello, If you are interested, contact me on slack @ Hirmay Sandesara.

**Comment by GemmaDawson** [comment]
Unfortunately, this project will not be continuing in QAMP Fall 2022
