### ISSUE TITLE
Qutrit circuits and simulations in Qiskit

### ISSUE THREAD

**Issue by nathanearnestnoble** [qiskit-advocate/qamp-fall-22#39]
### Description

With the development of Qiskit Pulse, one is able to program IBM Quantum Computers at the pulse level.   This allows users to explore computation which leverages higher energy states in the transmon (see 1) or 2) ).  However, if one wishes to stay in the abstract quantum circuit, Qiskit does not have a proper means to deal with qutrit based circuits or simulation.   To this end, this project will enable qutrit quantum circuits and simulations possible in the Qiskit environment. 

### Deliverables

- Qudit quantum circuits and possible transpilation methods
- qutrit quantum simulation backend

### Mentors details

- Mentor 1
  - Name: Nathan Earnest-Noble
  - GitHub ID: @nathanearnestnoble
  - What they do: Quantum Application Researcher and quantum software integration lead

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - proficient in Qiskit
    - familiarity with linear algebra
  - Nice to have:
    - interest in qutrit/qudit based quantum computation

**Comment by born-2learn** [comment]
This sounds like a great project for QAMP, @nathanearnestnoble! I'm interested in working on this. May I know if the end goal also involves implementing popular quantum algorithms using qutrit-quantum circuits?

**Comment by deveshq** [comment]
Hi @nathanearnestnoble, I found this project interesting. I want to join it. I would love to discuss the project, its objective, and its requirements.

**Comment by tinyRickk** [comment]
@nathanearnestnoble Hi, I am Aman. I am very interested in this project, I myself wished to introduce such a project in research (to describe and explore the changing behaviour of algorithms for qutrits). I have done some Hamiltonian simulations and Blind quantum Computation in past. I am very eager to work in this project.

**Comment by ssawarn** [comment]
I am interested in working. DM me on @stoick (slack)

**Comment by Pranshi24** [comment]
Hi @nathanearnestnoble   I am interested in working on this project, I am working as a Quantum Researcher at Deloitte, and I have experience in using Qiskit as well. This will be a good experience for me. Let me know if we can connect on Slack to discuss more.

**Comment by robertloredo** [comment]
Hi @nathanearnestnoble ! Sign me up if room available! Looking forward to it! 👍

**Comment by shraddha-aangiras** [comment]
Hello @nathanearnestnoble ! I'm really interested in working on this project. Would love to talk on Slack and discuss on this. I'm proficient with both Qiskit and linear algebra and this would be an amazing opportunity for me.

**Comment by ShivaniRajput11** [comment]
Hello @nathanearnestnoble! I'm interested in working on this. I do have experince in Qiskit as well as familiarity with linear algebra
familiarity with linear algebra

**Comment by scottoshiro2** [comment]
Hi @nathanearnestnoble I am very interested in working on this project, enabling qutrit quantum circuits and simulation. I am experienced in qiskit, open pulse and python.

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by nathanearnestnoble** [comment]
[QAMP Qutrits - Checkpoint 1 - Full.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9792171/QAMP.Qutrits.-.Checkpoint.1.-.Full.pptx)

**Comment by Stoick** [comment]
I am not in this class wrong email

**Comment by born-2learn** [comment]
**Written Project Update:** from @born-2learn @scottoshiro2 @tinyRickk 

**Qutrit/Qudit Noise modeling & Simulations in Qiskit:** 
Understood the program execution flow of the NoiseModel class and the realization of different errors, thermal relaxation error being one of them. Recreated the Choi matrix and Kraus representation of the Quantum channel in the Qiskit-qudits package created by us. Next step: Generalize the noise to qutrits/qudits.

![image](https://user-images.githubusercontent.com/42010556/201560901-d0ab6631-5bf6-47eb-93e9-00447cbc01e7.png)

![image](https://user-images.githubusercontent.com/42010556/201560934-2b19efa7-4b46-417e-bc9d-dd3df0935fd6.png)

![image](https://user-images.githubusercontent.com/42010556/201560946-c40730ab-973a-4b54-a1ff-cc4e9083ddca.png)

![image](https://user-images.githubusercontent.com/42010556/201560971-ea61c133-6f97-4071-9e78-cf2687bfe756.png)



**Qutrit/Qudit transpilation:**  In qiskit the transpilation step maps between gates by using the equivalence library. Decided to create a similar equivalence library for mapping between qutrit basis to native gates. Therefore, as a first step, built some native gate matrices and tested them with spin_simulator from qiskit cold atom.

![image](https://user-images.githubusercontent.com/42010556/201561252-81d29ab9-4390-460d-88aa-76a4139dc150.png)

![image](https://user-images.githubusercontent.com/42010556/201561267-d9a7dcc0-29f4-47de-b630-68e8afe1df9e.png)

![image](https://user-images.githubusercontent.com/42010556/201561297-755e9309-45f3-4e0a-805c-8b7eae169da6.png)


**Qutrit/Qudit gateset and visualization:** 
Pinpointed the library that is responsible for visualization of qubit circuits in qiskit and worked out the potential list of native gates that will form the basis gatesets for qutrits/qudits.

![image](https://user-images.githubusercontent.com/42010556/201561388-cb7e4c36-0ee3-4153-a9b0-bd9f01401148.png)

![image](https://user-images.githubusercontent.com/42010556/201561403-9bbdf512-1688-4b3b-9856-8ff56f6e4227.png)

![image](https://user-images.githubusercontent.com/42010556/201561429-c35a4cfa-98c4-4fda-bc49-8b251a7d2f0b.png)

@GemmaDawson @HuangJunye please find the update posted here, thanks!

**Comment by born-2learn** [comment]
[QAMP Qutrits - Final Presentation - Full.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/10230736/QAMP.Qutrits.-.Final.Presentation.-.Full.pptx)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
