### ISSUE TITLE
Implementing generalized measurements with mid-circuit measurements

### ISSUE THREAD

**Issue by alirezaseif-ibm** [qiskit-advocate/qamp-fall-22#4]
### Description

Positive operator valued measures (POVMs) describe generalized quantum measurements. They are useful for efficient extraction of information in quantum information processing tasks. These measurements can be implemented using Neumark extension by coupling the system to another auxiliary system that is typically of the same size and performing a projective measurement on the extended system. However, it has been shown that [Phys. Rev. A 77, 052104] it is possible to construct a binary search tree with a depth logarithmic in the number of possible outcomes and experimentally implement these measurements by coupling the system to a single auxiliary qubit that is measured iteratively together with conditional operation followed by each measurement. 

Here, we would like to implement these measurements using a single auxiliary qubit with mid-circuit measurements and conditional logics. 

### Deliverables

Demonstration of the tetrad measurement as shown in [Phys. Rev. A 77, 052104] using the Neumark extension and the binary tree approach with a blog post highlighting qiskit's dynamic circuits and conditional logic capabilities. 

### Mentors details

- Mentor 1
  - Name: Alireza Seif 
  - GitHub ID: alireza-seif
  - What they do: Researcher on Qiskit Leap 
- Mentor 2
  - Name: Derek Wang
  - GitHub ID: Derek-Wang
  - What they do: Researcher on Qiskit Leap 

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Proficient in Qiskit
    - Basic knowledge of quantum information theory
  - Nice to have:
    - Experience in Qiskit open source contributions

**Comment by zlatko-minev** [comment]
Great project and we get to work together

**Comment by tinyRickk** [comment]
Hi @alirezaseif-ibm, 
I am Aman, I am very much interested to work in this project and satisfy the requirement. I have worked in nuclear Hamiltonian simulations, error mitigation and blind quantum computation. I have skimmed through the paper and find it very interesting.

**Comment by gideonuchehara** [comment]
Hello @alirezaseif-ibm,
 
I am interested in this project. As part of my responsibilities at Xanadu, I create topical and engaging content related to quantum computing, and quantum machine learning. For example, I am currently creating a content on Open Quantum Systems and working on how to implement POVM using PennyLanne. Since I started working on this project, I have found it very exciting reading papers on the different methods of implementation of POVM. Also, considering the fact that most of the existing methods require extensive resources to work, I would like to explore ways to reduce the resource requirements as the paper for this project suggests.

I would greatly appreciate the opportunity to work on this project.

**Comment by petr-ivashkov** [comment]
Hello @GemmaDawson,

kindly add me to the issue!

**Comment by derek-wang-ibm** [comment]
Hi @GemmaDawson commenting and tagging you as requested

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by petr-ivashkov** [comment]
Hi @GemmaDawson, our checkpoint 1 materials are in our [repo](https://github.com/ibm-q-collaboration/qamp-generalized-measurements). I will attach them here as well.

[POVM_Checkpoint_1.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9745251/POVM_Checkpoint_1.pptx)

**Comment by gideonuchehara** [comment]
Hello @GemmaDawson, please find attached our checkpoint 2 material. The short update and a visual representation of our project are contained in the attached pdf file. The link to the repo is [here](https://github.com/ibm-q-collaboration/qamp-generalized-measurements/tree/master/checkpoint_02). Thanks
[Implementing_generalized_measurements_with_mid_circuit_measurements.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9924355/Implementing_generalized_measurements_with_mid_circuit_measurements.pdf)

**Comment by petr-ivashkov** [comment]
Hi @GemmaDawson! Please find attached our final presentation. We are currently working on the final version of our Jupyter notebook and will update you ASAP.
[Final presentation (1).pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/10254425/Final.presentation.1.pptx)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟

**Comment by HuangJunye** [comment]
@gideonuchehara @derek-wang-ibm @petr-ivashkov @alirezaseif-ibm Congrats for publishing the results on PRX Quantum! I am so happy to see that. Awesome work! https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.5.030315

**Comment by petr-ivashkov** [comment]
> @gideonuchehara @derek-wang-ibm @petr-ivashkov @alirezaseif-ibm Congrats for publishing the results on PRX Quantum! I am so happy to see that. Awesome work! https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.5.030315

Thank you, Junye! It's been a great journey. Thanks to QAMP for initiating this project.

**Comment by derek-wang-ibm** [comment]
Thanks, Junye! Yes, we are very grateful for QAMP and in fact acknowledged the program in our paper:

> We thank the organizers of the Qiskit Advocate Mentorship Program (QAMP) by IBM Quantum, where this
work was initiated

**Comment by gideonuchehara** [comment]
Thank you very much @HuangJunye. I am very grateful for being part of this QAMP project.

**Comment by HuangJunye** [comment]
> Thanks, Junye! Yes, we are very grateful for QAMP and in fact acknowledged the program in our paper:
> 
> > We thank the organizers of the Qiskit Advocate Mentorship Program (QAMP) by IBM Quantum, where this
> > work was initiated

Thank you for acknowledging QAMP!
