### ISSUE TITLE
Qiskit Runtime Documentation & Tutorials 

### ISSUE THREAD

**Issue by kt474** [qiskit-advocate/qamp-fall-22#40]
### Description

[Qiskit Runtime](https://github.com/Qiskit/qiskit-ibm-runtime) is a relatively new architecture that streamlines quantum computations with the goal of executing quantum circuits more efficiently. We recently implemented flexible sessions which allow multiple calls to primitives within the same session. Since this is a pretty big change, there is a need for more updated documentation and tutorials. If interested, any open issues in [qiskit-ibm-runtime](https://github.com/Qiskit/qiskit-ibm-runtime/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) can also be worked on. 

Related Issue: https://github.com/Qiskit/qiskit-ibm-runtime/issues/462

### Deliverables

- Updated documentation on how flexible sessions work (maybe in both qiskit-ibm-provider and qiskit-ibm-runtime) and any other new features
- Updated tutorials

### Mentors details

- Mentor 1
  - Name: Kevin Tian 
  - GitHub ID: @kt474
  - What they do: Software Developer for IBM Quantum, mostly `qiskit-ibm-runtime`
- Mentor 2
  - Name: Junye Huang
  - GitHub ID: @HuangJunye
  - What they do: Quantum Developer Advocate and part of Qiskit advocate squad

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Some experience with qiskit and git 
  - Nice to have:
    - Knowledge in qiskit provider and runtime repos

**Comment by TMuehge** [comment]
I would be interested especially in creating tutorials / demos in the context of the chemical industry. I would use this project to get a deeper insight into qiskit runtime as well-

**Comment by Pranshi24** [comment]
Hi @kt474  I am interested in working on this project, I am working as a Quantum Researcher at Deloitte, and I have experience in using Qiskit-Runtime as well. This will be a good experience for me. Let me know if we can connect on Slack to discuss more.

**Comment by ShivaniRajput11** [comment]
Hello @kt474  @HuangJunye, I am interested in working on this project. I am Bsc(H) Physics graduate student.Currently I am working as Research Associate at Univeristy of Delhi(India).Wanted to be a part of this project and give my contribution. I do have experince with qiskit and git both

**Comment by kt474** [comment]
Sorry, due to lack of resources and other priorities we are going to close this issue
