### ISSUE TITLE
Pulse backend in qiskit experiments

### ISSUE THREAD

**Issue by eggerdj** [qiskit-advocate/qamp-fall-22#5]
### Description

Qiskit Experiments (QE) is a framework that allows users to easily run experiments to, for example, calibrate or characterize the pulses that implement a quantum gate. QE provides a library of experiments to perform these tasks (fine amplitude calibration, drag, etc...). Currently, each experiment is tested using a fake backend that hard-codes the experimental response of a real backend. This (a) limits our testing abilities and (b) limits the tutorials that we can write. In the meantime, Qiskit Dynamics has emerged as a viable Qiskit pulse-level simulator that allows users to simulate pulse schedules. 

The aim of this project is to develop a backend capable of simulating pulse schedules with Qiskit Dynamics to enable tutorials and tests in QE.

### Deliverables

The project has the following deliverables:
* Create a backend for single-qubit characterization and calibration experiments that is capable of simulating the pulse schedules embedded in the circuit.
* Update the existing calibration tutorial to use this backend.
* Write new tutorials on qubit calibration and characterization.

Stretch objectives might include
* Writing backends for readout experiments and two-qubit experiments.
* Writing tutorials for readout and two-qubit experiments.

### Mentors details

- Mentor 1
  - Name: Daniel Egger
  - GitHub ID: @eggerdj
  - What they do: Quantum Applications Research and Software

### Number of mentees

2

### Type of mentees

- Mentee 1 and 2
  - Required:
    - Qiskit proficiency and python programming
    - An understanding of Hamiltonian dynamics
    - Knowledge of/ experience with Qiskit Pulse
  - Nice to have:
    - Has used Qiskit Experiments
    - Has used Qiskit Dynamics
    - Knowledge of quantum gate calibration

**Comment by deveshq** [comment]
Hi @eggerdj, I found this project interesting. I want to join it. I have some experience with Hamiltonian simulations using qiskit and currently working on quantum simulations. I have some knowledge of Qiskit Pulse.
I would love to discuss the project, its objective, and requirements.

**Comment by deveshq** [comment]
Hi @eggerdj, a gentle reminder. Please respond to this comment for confirmation that I can apply for this project in QAMP. 
@HuangJunye, please help.

**Comment by Qcatty** [comment]
I would like to join this project, I have experience with qiskit, also with Variational algorithms.

**Comment by HuangJunye** [comment]
@deveshq Sorry for the late reply. Yes you can go ahead and select the project in the application form.

**Comment by rupeshknn** [comment]
Hey @GemmaDawson can you assign me to this project?

**Comment by bicycle315** [comment]
@GemmaDawson I'm also assigned to this project! (Jeongwon Kim)

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by rupeshknn** [comment]
Checkpoint 1:
[qamp_fall22_checkpoint1.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9745095/qamp_fall22_checkpoint1.pdf)

**Comment by bicycle315** [comment]
Checkpoint 2:
[checkpoint2.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/9921151/checkpoint2.pdf)
![image](https://user-images.githubusercontent.com/56623045/199736870-110ad0fe-128c-4588-bd3d-ed661460a1d4.png)

**Comment by GemmaDawson** [comment]
@bicycle315 - thank you for the report.  Please do not forget that you need to add an image as well.

**Comment by GemmaDawson** [comment]
Thank you @bicycle315

**Comment by bicycle315** [comment]
[qamp_fall22_final_checkpoint_1208_pdf.pdf](https://github.com/qiskit-advocate/qamp-fall-22/files/10184339/qamp_fall22_final_checkpoint_1208_pdf.pdf)

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
