### ISSUE TITLE
A Qiskit tutorial that covers UnitarySyntheisPlugin and Approximate Quantum Compiler as an implementation

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-advocate/qamp-fall-22#7]
### Description

Recently a new extension was introduced in Qiskit's transpiler - a unitary synthesis plugin API (https://qiskit.org/documentation/apidoc/transpiler_plugins.html). This API provides a hook point for external python packages to implement their own synthesis techniques and have them seamlessly exposed as opt-in options to users when they run. The aim of this project is to write a new tutorial that explains the plugin API and a particular implementation of this plugin, approximate quantum compiler (https://qiskit.org/documentation/apidoc/synthesis_aqc.html) that was introduced at the same time as the plugin API. The proposed tutorial should give a comprehensive point of view to unitary synthesis, API, and AQC from an end-user point of view and from a Qiskit developer perspective.

### Deliverables

A tutorial, jupyter notebook for Qiskit Terra that covers three main topics: unitary syntheis, plugin API and approximate quantum compiler.

### Mentors details

Anton Dekusar, @adekusar-drl
Research Software Engineer / Qiskit Machine Learning contributor

### Number of mentees

1

### Type of mentees

What is required:

- Excellent writing skills and proficiency in jupyter notebook
- Basic knowledge of quantum computing
- Good knowledge of Qiskit transpiler would be really helpful

**Comment by Pranshi24** [comment]
Hi @adekusar-drl   I am interested in working on this project, I am working as a Quantum Researcher at Deloitte, and I have experience in using Qiskit as well. This will be a good experience for me. Let me know if we can connect on Slack to discuss more.

**Comment by adekusar-drl** [comment]
I'm closing this issue as I will be busy in another project.
