### ISSUE TITLE
Explore kernel based algorithms and extend the QuantumKernel tutorial

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-advocate/qamp-fall-22#9]
### Description

In this project we will explore applicability of quantum kernels in various classical algorithms. Quantum kernel itself is already implemented in Qiskit Machine Learning, there's a thin wrapper of the classical SVM from scikit-learn, thus we can solve classification and regression problems by evaluating a quantum kernel and feeding the kernel to the classical algorithms. But there are more things can be done with kernels. For instance, kernel PCA, clustering, etc. The goal of the project is to try out these classical algorithms in conjunction with quantum kernel and see what can be implemented. The scope of the project is not limited to these well-known algorithms. A mentee in the project may come up with their own ideas.

### Deliverables

An extended version of the existing quantum kernel tutorial or a new one, dedicated tutorial, on the applicability of quantum kernels for ML algorithms.

### Mentors details

Anton Dekusar, @adekusar-drl
Research Software Engineer / Qiskit Machine Learning contributor
There may be other mentors in this project.

### Number of mentees

1

### Type of mentees

What is required:
- Excellent writing skills and proficiency in jupyter notebook and python
- Proficiency in classical machine learning
- Some knowledge of quantum computing

**Comment by Tim-Li** [comment]
Hi, I am interested in this topic. 
I have used QSVM and SVM on tumor metastasis data and compared their effects. The results are expected to be published in the BIBE2022 conference paper. 
Therefore, I think we can continue to study different Quantum kernel-based Algorithms used in tumor metastasis data to see if they can show advantages. On the other hand, I think it can also apply in DeepSDF-related research to see if there is a way to show the potential of quantum advantage.

**Comment by Tim-Li** [comment]
Hi, @adekusar-drl 
I am interested in this topic. 
I have used QSVM and SVM on tumor metastasis data and compared their effects. The results are expected to be published in the BIBE2022 conference paper. Therefore, I think we can continue to study different Quantum kernel-based Algorithms used in tumor metastasis data to see if they can show advantages and make tutorials.

**Comment by derwind** [comment]
Hello @adekusar-drl I submitted my application to this issue as 2nd choice. I would like to discus about the detail. Thank you.

**Comment by adekusar-drl** [comment]
@derwind this project is already assigned to a mentee, sorry.

**Comment by derwind** [comment]
@adekusar-drl Okay, I see. Thanks for getting back to me. Looking forward to your results!

**Comment by VasilyBokov** [comment]
@GemmaDawson

**Comment by GemmaDawson** [comment]
Please add your Checkpoint 1 presentation materials.

**Comment by VasilyBokov** [comment]
[Quantum kernels. QAMP - 1.pptx](https://github.com/qiskit-advocate/qamp-fall-22/files/9777028/Quantum.kernels.QAMP.-.1.pptx)
[https://docs.google.com/presentation/d/1PJxXP3Bcuj5ayPI4OvyZvsqVpZIAeyvPWTY4ZD_YfO0/edit?usp=sharing](url)

@GemmaDawson  Hello, Gemma! Sorry for the delay. I attached the file.

**Comment by GemmaDawson** [comment]
@VasilyBokov - thank you!  FYI: the first PPTX link works but unfortunately, the Google Doc link does not work.

**Comment by VasilyBokov** [comment]
The general idea of our project is to harness quantum computing for kernel calculation problems. The most natural way of using kernels is a classification problem, in particular SVM. Qiskit already has some tutorials on this topic and the general objective here is to extend and deepen those materials.
We started the journey with the investigation main concepts of kernel calculations on a quantum computer, encoding techniques, and the NISQ device's capacity. Further, a toy model of quantum-assisted kernel PCA was created and acceptable results were obtained.
Currently, we are studying the quantum kernel implementation for novelty detection tasks based on One-Class SVM model. The kernel itself can be computed with the help of a SWAP test of an inverse circuit if its structure does not depend on data. Depending of hardware capacity, we are planning to consider 4,8,16 dimensional datasets. We expect to leverage an effective encoding algorithm for kernel calculations and find an appropriate data set for demonstration.

<img width="1335" alt="Kernel PCA" src="https://user-images.githubusercontent.com/62181457/199764865-dae77a98-256e-4f6e-8556-caf532eec67d.png">

**Comment by GemmaDawson** [comment]
@VasilyBokov - please upload your Final Showcase presentation materials, and if needed, update the project Title and/or description.

**Comment by VasilyBokov** [comment]
@GemmaDawson here are my presentation materials. Also, I updated the project description above. 

https://docs.google.com/presentation/d/15YMaZ_YJYhoLHW8b7AZsgoAFUKZiTMBY6QntdnVwTXU/edit?usp=sharing

**Comment by GemmaDawson** [comment]
Congratulations on completing all the requirements for QAMP Fall 2022!! 🌟🌟🌟
